/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedPlatformBillingRouteImport } from './routes/_authenticated/platform/billing'
import { Route as AuthenticatedPlatformCompareRouteImport } from './routes/_authenticated/platform/compare'
import { Route as AuthenticatedPlatformPlansRouteImport } from './routes/_authenticated/platform/plans'
import { Route as AuthenticatedPlatformRequestsRouteImport } from './routes/_authenticated/platform/requests'
import { Route as AuthenticatedPlatformTenantsRouteImport } from './routes/_authenticated/platform/tenants'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedStudentSlugRouteImport } from './routes/_authenticated/student/$slug'
import { Route as AuthenticatedAppSlugIndexRouteImport } from './routes/_authenticated/app/$slug/index'
import { Route as AuthenticatedAppSlugAccountsRouteImport } from './routes/_authenticated/app/$slug/accounts'
import { Route as AuthenticatedAppSlugCircleReportRouteImport } from './routes/_authenticated/app/$slug/circle-report'
import { Route as AuthenticatedAppSlugCirclesRouteImport } from './routes/_authenticated/app/$slug/circles'
import { Route as AuthenticatedAppSlugLinksRouteImport } from './routes/_authenticated/app/$slug/links'
import { Route as AuthenticatedAppSlugManagementRouteImport } from './routes/_authenticated/app/$slug/management'
import { Route as AuthenticatedAppSlugProgressRouteImport } from './routes/_authenticated/app/$slug/progress'
import { Route as AuthenticatedAppSlugRecordsRouteImport } from './routes/_authenticated/app/$slug/records'
import { Route as AuthenticatedAppSlugReportsRouteImport } from './routes/_authenticated/app/$slug/reports'
import { Route as AuthenticatedAppSlugSettingsRouteImport } from './routes/_authenticated/app/$slug/settings'
import { Route as AuthenticatedAppSlugStatsRouteImport } from './routes/_authenticated/app/$slug/stats'
import { Route as AuthenticatedAppSlugStudentsRouteImport } from './routes/_authenticated/app/$slug/students'
import { Route as AuthenticatedAppSlugSubscriptionRouteImport } from './routes/_authenticated/app/$slug/subscription'
import { Route as AuthenticatedAppSlugTracksRouteImport } from './routes/_authenticated/app/$slug/tracks'
import { Route as AuthenticatedAppSlugVolunteersRouteImport } from './routes/_authenticated/app/$slug/volunteers'
import { Route as ApiPublicWebhooksPaymentsRouteImport } from './routes/api/public/webhooks/payments'
import { Route as AuthenticatedAppSlugStudentsStudentIdRouteImport } from './routes/_authenticated/app/$slug/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/platform/',
    path: '/platform/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformBillingRoute =
  AuthenticatedPlatformBillingRouteImport.update({
    id: '/platform/billing',
    path: '/platform/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformCompareRoute =
  AuthenticatedPlatformCompareRouteImport.update({
    id: '/platform/compare',
    path: '/platform/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformPlansRoute =
  AuthenticatedPlatformPlansRouteImport.update({
    id: '/platform/plans',
    path: '/platform/plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRequestsRoute =
  AuthenticatedPlatformRequestsRouteImport.update({
    id: '/platform/requests',
    path: '/platform/requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformTenantsRoute =
  AuthenticatedPlatformTenantsRouteImport.update({
    id: '/platform/tenants',
    path: '/platform/tenants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSlugRoute =
  AuthenticatedStudentSlugRouteImport.update({
    id: '/student/$slug',
    path: '/student/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugIndexRoute =
  AuthenticatedAppSlugIndexRouteImport.update({
    id: '/app/$slug/',
    path: '/app/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugAccountsRoute =
  AuthenticatedAppSlugAccountsRouteImport.update({
    id: '/app/$slug/accounts',
    path: '/app/$slug/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugCircleReportRoute =
  AuthenticatedAppSlugCircleReportRouteImport.update({
    id: '/app/$slug/circle-report',
    path: '/app/$slug/circle-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugCirclesRoute =
  AuthenticatedAppSlugCirclesRouteImport.update({
    id: '/app/$slug/circles',
    path: '/app/$slug/circles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugLinksRoute =
  AuthenticatedAppSlugLinksRouteImport.update({
    id: '/app/$slug/links',
    path: '/app/$slug/links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugManagementRoute =
  AuthenticatedAppSlugManagementRouteImport.update({
    id: '/app/$slug/management',
    path: '/app/$slug/management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugProgressRoute =
  AuthenticatedAppSlugProgressRouteImport.update({
    id: '/app/$slug/progress',
    path: '/app/$slug/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugRecordsRoute =
  AuthenticatedAppSlugRecordsRouteImport.update({
    id: '/app/$slug/records',
    path: '/app/$slug/records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugReportsRoute =
  AuthenticatedAppSlugReportsRouteImport.update({
    id: '/app/$slug/reports',
    path: '/app/$slug/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugSettingsRoute =
  AuthenticatedAppSlugSettingsRouteImport.update({
    id: '/app/$slug/settings',
    path: '/app/$slug/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugStatsRoute =
  AuthenticatedAppSlugStatsRouteImport.update({
    id: '/app/$slug/stats',
    path: '/app/$slug/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugStudentsRoute =
  AuthenticatedAppSlugStudentsRouteImport.update({
    id: '/app/$slug/students',
    path: '/app/$slug/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugSubscriptionRoute =
  AuthenticatedAppSlugSubscriptionRouteImport.update({
    id: '/app/$slug/subscription',
    path: '/app/$slug/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugTracksRoute =
  AuthenticatedAppSlugTracksRouteImport.update({
    id: '/app/$slug/tracks',
    path: '/app/$slug/tracks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSlugVolunteersRoute =
  AuthenticatedAppSlugVolunteersRouteImport.update({
    id: '/app/$slug/volunteers',
    path: '/app/$slug/volunteers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksPaymentsRoute =
  ApiPublicWebhooksPaymentsRouteImport.update({
    id: '/api/public/webhooks/payments',
    path: '/api/public/webhooks/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSlugStudentsStudentIdRoute =
  AuthenticatedAppSlugStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedAppSlugStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/plans': typeof PlansRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/m/$slug': typeof MSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/v/$slug': typeof VSlugRoute
  '/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/platform/compare': typeof AuthenticatedPlatformCompareRoute
  '/platform/plans': typeof AuthenticatedPlatformPlansRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/student/$slug': typeof AuthenticatedStudentSlugRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/app/$slug/accounts': typeof AuthenticatedAppSlugAccountsRoute
  '/app/$slug/circle-report': typeof AuthenticatedAppSlugCircleReportRoute
  '/app/$slug/circles': typeof AuthenticatedAppSlugCirclesRoute
  '/app/$slug/links': typeof AuthenticatedAppSlugLinksRoute
  '/app/$slug/management': typeof AuthenticatedAppSlugManagementRoute
  '/app/$slug/progress': typeof AuthenticatedAppSlugProgressRoute
  '/app/$slug/records': typeof AuthenticatedAppSlugRecordsRoute
  '/app/$slug/reports': typeof AuthenticatedAppSlugReportsRoute
  '/app/$slug/settings': typeof AuthenticatedAppSlugSettingsRoute
  '/app/$slug/stats': typeof AuthenticatedAppSlugStatsRoute
  '/app/$slug/students': typeof AuthenticatedAppSlugStudentsRouteWithChildren
  '/app/$slug/subscription': typeof AuthenticatedAppSlugSubscriptionRoute
  '/app/$slug/tracks': typeof AuthenticatedAppSlugTracksRoute
  '/app/$slug/volunteers': typeof AuthenticatedAppSlugVolunteersRoute
  '/api/public/webhooks/payments': typeof ApiPublicWebhooksPaymentsRoute
  '/app/$slug/': typeof AuthenticatedAppSlugIndexRoute
  '/app/$slug/students/$studentId': typeof AuthenticatedAppSlugStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/plans': typeof PlansRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/m/$slug': typeof MSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/v/$slug': typeof VSlugRoute
  '/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/platform/compare': typeof AuthenticatedPlatformCompareRoute
  '/platform/plans': typeof AuthenticatedPlatformPlansRoute
  '/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/student/$slug': typeof AuthenticatedStudentSlugRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/app/$slug/accounts': typeof AuthenticatedAppSlugAccountsRoute
  '/app/$slug/circle-report': typeof AuthenticatedAppSlugCircleReportRoute
  '/app/$slug/circles': typeof AuthenticatedAppSlugCirclesRoute
  '/app/$slug/links': typeof AuthenticatedAppSlugLinksRoute
  '/app/$slug/management': typeof AuthenticatedAppSlugManagementRoute
  '/app/$slug/progress': typeof AuthenticatedAppSlugProgressRoute
  '/app/$slug/records': typeof AuthenticatedAppSlugRecordsRoute
  '/app/$slug/reports': typeof AuthenticatedAppSlugReportsRoute
  '/app/$slug/settings': typeof AuthenticatedAppSlugSettingsRoute
  '/app/$slug/stats': typeof AuthenticatedAppSlugStatsRoute
  '/app/$slug/students': typeof AuthenticatedAppSlugStudentsRouteWithChildren
  '/app/$slug/subscription': typeof AuthenticatedAppSlugSubscriptionRoute
  '/app/$slug/tracks': typeof AuthenticatedAppSlugTracksRoute
  '/app/$slug/volunteers': typeof AuthenticatedAppSlugVolunteersRoute
  '/api/public/webhooks/payments': typeof ApiPublicWebhooksPaymentsRoute
  '/app/$slug': typeof AuthenticatedAppSlugIndexRoute
  '/app/$slug/students/$studentId': typeof AuthenticatedAppSlugStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/plans': typeof PlansRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/m/$slug': typeof MSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/v/$slug': typeof VSlugRoute
  '/_authenticated/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/_authenticated/platform/compare': typeof AuthenticatedPlatformCompareRoute
  '/_authenticated/platform/plans': typeof AuthenticatedPlatformPlansRoute
  '/_authenticated/platform/requests': typeof AuthenticatedPlatformRequestsRoute
  '/_authenticated/platform/tenants': typeof AuthenticatedPlatformTenantsRoute
  '/_authenticated/student/$slug': typeof AuthenticatedStudentSlugRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/app/$slug/accounts': typeof AuthenticatedAppSlugAccountsRoute
  '/_authenticated/app/$slug/circle-report': typeof AuthenticatedAppSlugCircleReportRoute
  '/_authenticated/app/$slug/circles': typeof AuthenticatedAppSlugCirclesRoute
  '/_authenticated/app/$slug/links': typeof AuthenticatedAppSlugLinksRoute
  '/_authenticated/app/$slug/management': typeof AuthenticatedAppSlugManagementRoute
  '/_authenticated/app/$slug/progress': typeof AuthenticatedAppSlugProgressRoute
  '/_authenticated/app/$slug/records': typeof AuthenticatedAppSlugRecordsRoute
  '/_authenticated/app/$slug/reports': typeof AuthenticatedAppSlugReportsRoute
  '/_authenticated/app/$slug/settings': typeof AuthenticatedAppSlugSettingsRoute
  '/_authenticated/app/$slug/stats': typeof AuthenticatedAppSlugStatsRoute
  '/_authenticated/app/$slug/students': typeof AuthenticatedAppSlugStudentsRouteWithChildren
  '/_authenticated/app/$slug/subscription': typeof AuthenticatedAppSlugSubscriptionRoute
  '/_authenticated/app/$slug/tracks': typeof AuthenticatedAppSlugTracksRoute
  '/_authenticated/app/$slug/volunteers': typeof AuthenticatedAppSlugVolunteersRoute
  '/api/public/webhooks/payments': typeof ApiPublicWebhooksPaymentsRoute
  '/_authenticated/app/$slug/': typeof AuthenticatedAppSlugIndexRoute
  '/_authenticated/app/$slug/students/$studentId': typeof AuthenticatedAppSlugStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/features'
    | '/plans'
    | '/reset-password'
    | '/roles'
    | '/dashboard'
    | '/invite/$token'
    | '/m/$slug'
    | '/s/$slug'
    | '/v/$slug'
    | '/platform/billing'
    | '/platform/compare'
    | '/platform/plans'
    | '/platform/requests'
    | '/platform/tenants'
    | '/student/$slug'
    | '/platform/'
    | '/student/'
    | '/app/$slug/accounts'
    | '/app/$slug/circle-report'
    | '/app/$slug/circles'
    | '/app/$slug/links'
    | '/app/$slug/management'
    | '/app/$slug/progress'
    | '/app/$slug/records'
    | '/app/$slug/reports'
    | '/app/$slug/settings'
    | '/app/$slug/stats'
    | '/app/$slug/students'
    | '/app/$slug/subscription'
    | '/app/$slug/tracks'
    | '/app/$slug/volunteers'
    | '/api/public/webhooks/payments'
    | '/app/$slug/'
    | '/app/$slug/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/features'
    | '/plans'
    | '/reset-password'
    | '/roles'
    | '/dashboard'
    | '/invite/$token'
    | '/m/$slug'
    | '/s/$slug'
    | '/v/$slug'
    | '/platform/billing'
    | '/platform/compare'
    | '/platform/plans'
    | '/platform/requests'
    | '/platform/tenants'
    | '/student/$slug'
    | '/platform'
    | '/student'
    | '/app/$slug/accounts'
    | '/app/$slug/circle-report'
    | '/app/$slug/circles'
    | '/app/$slug/links'
    | '/app/$slug/management'
    | '/app/$slug/progress'
    | '/app/$slug/records'
    | '/app/$slug/reports'
    | '/app/$slug/settings'
    | '/app/$slug/stats'
    | '/app/$slug/students'
    | '/app/$slug/subscription'
    | '/app/$slug/tracks'
    | '/app/$slug/volunteers'
    | '/api/public/webhooks/payments'
    | '/app/$slug'
    | '/app/$slug/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/features'
    | '/plans'
    | '/reset-password'
    | '/roles'
    | '/_authenticated/dashboard'
    | '/invite/$token'
    | '/m/$slug'
    | '/s/$slug'
    | '/v/$slug'
    | '/_authenticated/platform/billing'
    | '/_authenticated/platform/compare'
    | '/_authenticated/platform/plans'
    | '/_authenticated/platform/requests'
    | '/_authenticated/platform/tenants'
    | '/_authenticated/student/$slug'
    | '/_authenticated/platform/'
    | '/_authenticated/student/'
    | '/_authenticated/app/$slug/accounts'
    | '/_authenticated/app/$slug/circle-report'
    | '/_authenticated/app/$slug/circles'
    | '/_authenticated/app/$slug/links'
    | '/_authenticated/app/$slug/management'
    | '/_authenticated/app/$slug/progress'
    | '/_authenticated/app/$slug/records'
    | '/_authenticated/app/$slug/reports'
    | '/_authenticated/app/$slug/settings'
    | '/_authenticated/app/$slug/stats'
    | '/_authenticated/app/$slug/students'
    | '/_authenticated/app/$slug/subscription'
    | '/_authenticated/app/$slug/tracks'
    | '/_authenticated/app/$slug/volunteers'
    | '/api/public/webhooks/payments'
    | '/_authenticated/app/$slug/'
    | '/_authenticated/app/$slug/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PlansRoute: typeof PlansRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MSlugRoute: typeof MSlugRoute
  SSlugRoute: typeof SSlugRoute
  VSlugRoute: typeof VSlugRoute
  ApiPublicWebhooksPaymentsRoute: typeof ApiPublicWebhooksPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/billing': {
      id: '/_authenticated/platform/billing'
      path: '/platform/billing'
      fullPath: '/platform/billing'
      preLoaderRoute: typeof AuthenticatedPlatformBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/compare': {
      id: '/_authenticated/platform/compare'
      path: '/platform/compare'
      fullPath: '/platform/compare'
      preLoaderRoute: typeof AuthenticatedPlatformCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/plans': {
      id: '/_authenticated/platform/plans'
      path: '/platform/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof AuthenticatedPlatformPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/requests': {
      id: '/_authenticated/platform/requests'
      path: '/platform/requests'
      fullPath: '/platform/requests'
      preLoaderRoute: typeof AuthenticatedPlatformRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/tenants': {
      id: '/_authenticated/platform/tenants'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof AuthenticatedPlatformTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/$slug': {
      id: '/_authenticated/student/$slug'
      path: '/student/$slug'
      fullPath: '/student/$slug'
      preLoaderRoute: typeof AuthenticatedStudentSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/': {
      id: '/_authenticated/app/$slug/'
      path: '/app/$slug'
      fullPath: '/app/$slug/'
      preLoaderRoute: typeof AuthenticatedAppSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/accounts': {
      id: '/_authenticated/app/$slug/accounts'
      path: '/app/$slug/accounts'
      fullPath: '/app/$slug/accounts'
      preLoaderRoute: typeof AuthenticatedAppSlugAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/circle-report': {
      id: '/_authenticated/app/$slug/circle-report'
      path: '/app/$slug/circle-report'
      fullPath: '/app/$slug/circle-report'
      preLoaderRoute: typeof AuthenticatedAppSlugCircleReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/circles': {
      id: '/_authenticated/app/$slug/circles'
      path: '/app/$slug/circles'
      fullPath: '/app/$slug/circles'
      preLoaderRoute: typeof AuthenticatedAppSlugCirclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/links': {
      id: '/_authenticated/app/$slug/links'
      path: '/app/$slug/links'
      fullPath: '/app/$slug/links'
      preLoaderRoute: typeof AuthenticatedAppSlugLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/management': {
      id: '/_authenticated/app/$slug/management'
      path: '/app/$slug/management'
      fullPath: '/app/$slug/management'
      preLoaderRoute: typeof AuthenticatedAppSlugManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/progress': {
      id: '/_authenticated/app/$slug/progress'
      path: '/app/$slug/progress'
      fullPath: '/app/$slug/progress'
      preLoaderRoute: typeof AuthenticatedAppSlugProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/records': {
      id: '/_authenticated/app/$slug/records'
      path: '/app/$slug/records'
      fullPath: '/app/$slug/records'
      preLoaderRoute: typeof AuthenticatedAppSlugRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/reports': {
      id: '/_authenticated/app/$slug/reports'
      path: '/app/$slug/reports'
      fullPath: '/app/$slug/reports'
      preLoaderRoute: typeof AuthenticatedAppSlugReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/settings': {
      id: '/_authenticated/app/$slug/settings'
      path: '/app/$slug/settings'
      fullPath: '/app/$slug/settings'
      preLoaderRoute: typeof AuthenticatedAppSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/stats': {
      id: '/_authenticated/app/$slug/stats'
      path: '/app/$slug/stats'
      fullPath: '/app/$slug/stats'
      preLoaderRoute: typeof AuthenticatedAppSlugStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/students': {
      id: '/_authenticated/app/$slug/students'
      path: '/app/$slug/students'
      fullPath: '/app/$slug/students'
      preLoaderRoute: typeof AuthenticatedAppSlugStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/subscription': {
      id: '/_authenticated/app/$slug/subscription'
      path: '/app/$slug/subscription'
      fullPath: '/app/$slug/subscription'
      preLoaderRoute: typeof AuthenticatedAppSlugSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/tracks': {
      id: '/_authenticated/app/$slug/tracks'
      path: '/app/$slug/tracks'
      fullPath: '/app/$slug/tracks'
      preLoaderRoute: typeof AuthenticatedAppSlugTracksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/$slug/volunteers': {
      id: '/_authenticated/app/$slug/volunteers'
      path: '/app/$slug/volunteers'
      fullPath: '/app/$slug/volunteers'
      preLoaderRoute: typeof AuthenticatedAppSlugVolunteersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/payments': {
      id: '/api/public/webhooks/payments'
      path: '/api/public/webhooks/payments'
      fullPath: '/api/public/webhooks/payments'
      preLoaderRoute: typeof ApiPublicWebhooksPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/$slug/students/$studentId': {
      id: '/_authenticated/app/$slug/students/$studentId'
      path: '/$studentId'
      fullPath: '/app/$slug/students/$studentId'
      preLoaderRoute: typeof AuthenticatedAppSlugStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedAppSlugStudentsRoute
    }
  }
}

interface AuthenticatedAppSlugStudentsRouteChildren {
  AuthenticatedAppSlugStudentsStudentIdRoute: typeof AuthenticatedAppSlugStudentsStudentIdRoute
}

const AuthenticatedAppSlugStudentsRouteChildren: AuthenticatedAppSlugStudentsRouteChildren =
  {
    AuthenticatedAppSlugStudentsStudentIdRoute:
      AuthenticatedAppSlugStudentsStudentIdRoute,
  }

const AuthenticatedAppSlugStudentsRouteWithChildren =
  AuthenticatedAppSlugStudentsRoute._addFileChildren(
    AuthenticatedAppSlugStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlatformBillingRoute: typeof AuthenticatedPlatformBillingRoute
  AuthenticatedPlatformCompareRoute: typeof AuthenticatedPlatformCompareRoute
  AuthenticatedPlatformPlansRoute: typeof AuthenticatedPlatformPlansRoute
  AuthenticatedPlatformRequestsRoute: typeof AuthenticatedPlatformRequestsRoute
  AuthenticatedPlatformTenantsRoute: typeof AuthenticatedPlatformTenantsRoute
  AuthenticatedStudentSlugRoute: typeof AuthenticatedStudentSlugRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedAppSlugAccountsRoute: typeof AuthenticatedAppSlugAccountsRoute
  AuthenticatedAppSlugCircleReportRoute: typeof AuthenticatedAppSlugCircleReportRoute
  AuthenticatedAppSlugCirclesRoute: typeof AuthenticatedAppSlugCirclesRoute
  AuthenticatedAppSlugLinksRoute: typeof AuthenticatedAppSlugLinksRoute
  AuthenticatedAppSlugManagementRoute: typeof AuthenticatedAppSlugManagementRoute
  AuthenticatedAppSlugProgressRoute: typeof AuthenticatedAppSlugProgressRoute
  AuthenticatedAppSlugRecordsRoute: typeof AuthenticatedAppSlugRecordsRoute
  AuthenticatedAppSlugReportsRoute: typeof AuthenticatedAppSlugReportsRoute
  AuthenticatedAppSlugSettingsRoute: typeof AuthenticatedAppSlugSettingsRoute
  AuthenticatedAppSlugStatsRoute: typeof AuthenticatedAppSlugStatsRoute
  AuthenticatedAppSlugStudentsRoute: typeof AuthenticatedAppSlugStudentsRouteWithChildren
  AuthenticatedAppSlugSubscriptionRoute: typeof AuthenticatedAppSlugSubscriptionRoute
  AuthenticatedAppSlugTracksRoute: typeof AuthenticatedAppSlugTracksRoute
  AuthenticatedAppSlugVolunteersRoute: typeof AuthenticatedAppSlugVolunteersRoute
  AuthenticatedAppSlugIndexRoute: typeof AuthenticatedAppSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlatformBillingRoute: AuthenticatedPlatformBillingRoute,
  AuthenticatedPlatformCompareRoute: AuthenticatedPlatformCompareRoute,
  AuthenticatedPlatformPlansRoute: AuthenticatedPlatformPlansRoute,
  AuthenticatedPlatformRequestsRoute: AuthenticatedPlatformRequestsRoute,
  AuthenticatedPlatformTenantsRoute: AuthenticatedPlatformTenantsRoute,
  AuthenticatedStudentSlugRoute: AuthenticatedStudentSlugRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedAppSlugAccountsRoute: AuthenticatedAppSlugAccountsRoute,
  AuthenticatedAppSlugCircleReportRoute: AuthenticatedAppSlugCircleReportRoute,
  AuthenticatedAppSlugCirclesRoute: AuthenticatedAppSlugCirclesRoute,
  AuthenticatedAppSlugLinksRoute: AuthenticatedAppSlugLinksRoute,
  AuthenticatedAppSlugManagementRoute: AuthenticatedAppSlugManagementRoute,
  AuthenticatedAppSlugProgressRoute: AuthenticatedAppSlugProgressRoute,
  AuthenticatedAppSlugRecordsRoute: AuthenticatedAppSlugRecordsRoute,
  AuthenticatedAppSlugReportsRoute: AuthenticatedAppSlugReportsRoute,
  AuthenticatedAppSlugSettingsRoute: AuthenticatedAppSlugSettingsRoute,
  AuthenticatedAppSlugStatsRoute: AuthenticatedAppSlugStatsRoute,
  AuthenticatedAppSlugStudentsRoute:
    AuthenticatedAppSlugStudentsRouteWithChildren,
  AuthenticatedAppSlugSubscriptionRoute: AuthenticatedAppSlugSubscriptionRoute,
  AuthenticatedAppSlugTracksRoute: AuthenticatedAppSlugTracksRoute,
  AuthenticatedAppSlugVolunteersRoute: AuthenticatedAppSlugVolunteersRoute,
  AuthenticatedAppSlugIndexRoute: AuthenticatedAppSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PlansRoute: PlansRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  InviteTokenRoute: InviteTokenRoute,
  MSlugRoute: MSlugRoute,
  SSlugRoute: SSlugRoute,
  VSlugRoute: VSlugRoute,
  ApiPublicWebhooksPaymentsRoute: ApiPublicWebhooksPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
